#!/usr/bin/env bash
#script to installl and configure nginx
apt-get update
apt-get install -y nginx
mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
echo "" > /etc/nginx/sites-available/default
cat <<END>> /etc/nginx/sites-available/default
server {
	listen   80 default_server;
	listen   [::]:80 default_server;
	root     /var/www/html;
	index    index.html index.htm;
}
END
service nginx restart
