#!/usr/bin/env bash
# to file or not to file
flie="school"
if [ -e "$file" ]
then
	echo "school file exits"
	if [ -s "$file" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$file" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
